language: node_js
node_js:
  - "0.8"
before_script:
  - npm install -g grunt-cli
  - "curl -o resources/js-test-driver/JsTestDriver-1.3.3d.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.3d.jar'"
  - "java -jar resources/js-test-driver/JsTestDriver-1.3.3d.jar --basePath resources/js-test-driver --config resources/js-test-driver/jsTestDriver.conf --port 5555 &"
  - "sleep 3"
  - "phantomjs resources/js-test-driver-phantomjs/phantomjs-jstd.js &"
  - "sleep 3"